### ISSUE TITLE
SF FNPRMS hasn't uploaded results from 7/4

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#130]
See https://github.com/mozilla-mobile/fenix-nightly-perftest-results/blob/d227ebd4ff02a8532287d9215d097b718f44aa3c/hanoob-results.csv – they're N/A or completely missing. This is both for MAIN and VIEW.

**Comment by mcomella** [comment]
@MarcLeclair Can you take a look?

**Comment by Malclir** [comment]
Fixed why it wasn't uploading, re running the tests currently.

**Comment by mcomella** [comment]
@MarcLeclair Can you comment why it wasn't working, in case we run into similar issues? Also, is this issue ready to be closed? We should probably open a new issue for re-running the tests.

**Comment by Malclir** [comment]
@mcomella  it wasn't working because of my local setup for my router. For some reason, OpenWRT was blocking the request from the desktop. The desktop is in a room where I can't get an ethernet cable to, so I connected the testing desktop to my regular desktop (through ethernet wire) that shares the wifi connection from my desktop. Not sure why it stopped working, but I just had to go change the settings in my router 😄
