### ISSUE TITLE
Web extension doesn't meet RC on higher end devices - issue #12515

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#135]

**Comment by mcomella** [comment]
@MarcLeclair Please update with info for ecsmyth

**Comment by sraturi** [comment]
#### Here is some information I got for **add-ons on MAIN** from poking around add-ons channels

There is some extension work that happens immediately at startup, so you should see an effect even if you don't load any page some extensions like uBlock register listeners on every page load (to see if any given resource load should be blocked or not) so Gecko stalls network requests until the extension framework comes online
to summarize: some work happens immediately, some at the first pageload. all depending on the add-ons

“The extension implementation is lazily loaded as much as possible, and some data is cached to reduce the cost of extension startup. For users, I suppose that blocking webRequest listeners (e.g. from uBlock Origin) are going to be a large contributor to perceived performance, because network requests are suspended until the extension has started + handled the request. Content scripts (especially with "run_at": "document_start") also have potential to affect performance of a web page.”

**Comment by mcomella** [comment]
Triage: we don't know which add-on to test with and haven't gotten an answer from the webExtensions team. Moving to main triage so we can review again next week.

**Comment by mcomella** [comment]
Triage: is this for pageload? Didn't meet page load RC? RC doesn't really matter right now. Most important thing for us is list of add-ons to test on start up. Only tested with ublock... should be no start up cost (besides ublock).

**Comment by mcomella** [comment]
Let's reopen when we deal with release criteria again – we're not quite sure what this is for.
