### ISSUE TITLE
Measure impact of collections on startup performance

### ISSUE THREAD

**Issue by ecsmyth** [mozilla-mobile/perf-frontend-issues#77]
Similar to analysis performed of open tabs impact on startup, measure the impact of the number of collections and the number of tabs per collection on startup time.

Consider
- 0-15 collections
- tabs/per collection in increments of 5 from 1 to 26

**Comment by emalysz** [comment]
Blocked on https://github.com/mozilla-mobile/fenix/issues/8561

**Comment by emalysz** [comment]
Here were our findings (time is in ms): 

<img width="700" alt="Screen Shot 2020-03-23 at 7 36 11 AM" src="https://user-images.githubusercontent.com/15795071/77327897-0c66fb00-6cd9-11ea-8159-207938ea005a.png">
<img width="657" alt="Screen Shot 2020-03-23 at 7 36 21 AM" src="https://user-images.githubusercontent.com/15795071/77327914-12f57280-6cd9-11ea-9b5b-9a7f43156b25.png">

____________________________________________________________
We noticed that there is a slight regression as we add collections or tabs/collection, but this can potentially be attributed to noise. We have re-prioritized issues accordingly.

Note: to do this analysis, I used a local version of FNPRMS to bind to collections instead of top sites.
