### ISSUE TITLE
Determine the future for cold startup measurement tools (FNPRMS)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#79]
We've been using FNPRMS to measure cold startup testing to homescreen performance but leaned on it as the best choice in the short term: we should re-evaluate if FNPRMS is the best solution in the long term.

### Acceptance criteria
- Determine if FNPRMS is the best (or a good enough) solution for startup to homescreen. Consider:
  - Do we want to measure using visual completeness? Can FNPRMS get us there?
- If not, provide an initial alternative to the team for discussion

**Comment by jimporter** [comment]
@mcomella I think it would make sense to keep FNPRMS around as the "universal mobile performance test driver", at least in the medium term. Since it's a separate repo, it would afford us a good deal of flexibility in making changes, and we could focus on making it easy for people to run perf tests and get results. (In the long term, perhaps we'd move this universal test driver into another repo, similar to how `mach` handles a lot of various utilities for desktop.)

In the short term, this would probably mean measuring things the way FNPRMS does now, but in the future, we could just change the underlying implementation. Then, users of FNPRMS wouldn't need to learn a new tool in order to get performance numbers.

**Comment by mcomella** [comment]
Thanks for the note, jimporter: I scheduled a meeting on Monday to discuss as a team what we think the next steps are. I agree that we should have a single unified runner to make it easy for folks to check their changes.

**Comment by mcomella** [comment]
We met as a group and decided that FNPRMS merged into the Browsertime harness is the way to go. acreskey, sparky, and co. are taking ownership of this in the future so we don't need to track this on this board. We'll have weekly check-ins to determine progress.
