### ISSUE TITLE
FNPRMS HANOOB Fennec 68 baseline (G5) may be incorrect (lower than actual)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#92]
As per #91, we noticed that the G5 uses "total" time rather than the non-total "fully drawn" time. afaict, fennec 68 should also display "total" time so we're using the wrong number. I think this because the `LAUNCHER` intent filter is in `LauncherActivity` but `BrowserApp` is the final app launched. I can't verify this behavior right now because I don't have a G5.

If this is true, the number will be lower than the actual number. We should 1) correct the code in times.py to use total time (or do #91) and 2) re-run our Fennec baseline numbers on the G5.

This problem may have affected a few of the devices bdekoz has taken baselines with as well though I don't think it should affect the Pixel 2. We should consider re-running here too.

**Comment by bdekoz** [comment]
So... since #91 is done, what to do when re-visiting this? This problem impacted the G5, the S10, and the S7. Since the closure of #91, the S10 and S7 hanoob numbers (and presumably G5) have all used the new scripts. So, at least for the month of May, these numbers should be correct. 

We don't have to re-run the tests and get new results, we just have to re-run the 'do_times.sh' script on existing results, which happens nightly, so...I'm going to close this and have Michael re-open if necessary.

Also, in the #91 notes, it's clear that we cannot be completely deterministic about total vs. non-total fully drawn time across android versions and devices. We can prefer total time, but have to settle for non-total time with the knowledge that the device in question can't do better.

**Comment by bdekoz** [comment]
try close

**Comment by mcomella** [comment]
Thanks for looking into this.

To be explicit, this is about the fennec (old Firefox for Android) baselines, not the fenix (or fennec-nightly) numbers.

> We don't have to re-run the tests and get new results, we just have to re-run the 'do_times.sh' script on existing results, which happens nightly, so

This is true but I doubt we have the logs from the original fennec 68 run so I think we need to re-run this anyway.

**Comment by Malclir** [comment]
So I got the following `20.06.08, 0.58368` from fennec using 68.6.0 build. I got the following output
[2020.06.08-hanoob.log](https://github.com/mozilla-mobile/perf-frontend-issues/files/4748944/2020.06.08-hanoob.log)

the `Fully drawn` didn't work, I had to switch the regex to `Displayed` to be able to even get the average out. Any thoughts @mcomella ?

**Comment by mcomella** [comment]
MarcLeclair linked to some old instructions which can be helpful: https://github.com/mozilla-mobile/perf-frontend-issues/issues/64#issuecomment-588479877

**Comment by Malclir** [comment]
Finally got the real numbers which are ` 1.1859599999999997` seconds on 68.6.0 build.
